import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Briefcase, Building2, GraduationCap, Users } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, Panel, PanelHeader, StatCard } from "@/components/common";
import { ChartCard, SimpleBarChart, SimplePieChart } from "@/components/charts";
import { dashboardApi, departmentsApi, placementsApi, placementApplicationsApi } from "@/api/campusApi";

export const Route=createFileRoute("/admin/dashboard")({head:()=>({meta:[{title:"Admin Dashboard — CampusConnect"}]}),component:AdminDashboard});
function AdminDashboard(){const [stats,setStats]=useState({}),[deps,setDeps]=useState([]),[drives,setDrives]=useState([]),[apps,setApps]=useState([]);useEffect(()=>{Promise.all([dashboardApi.admin(),departmentsApi.list(),placementsApi.list(),placementApplicationsApi.list()]).then(([s,d,p,a])=>{setStats(s||{});setDeps(d||[]);setDrives(p||[]);setApps(a||[])}).catch(e=>toast.error(e.response?.data?.message||"Unable to load dashboard"))},[]);const placement=[{name:"Applied",value:apps.length},{name:"Selected",value:apps.filter(a=>a.status==="Selected").length},{name:"Rejected",value:apps.filter(a=>a.status==="Rejected").length}];return <><PageHeader title="Institution Overview" description="Live snapshot from the CampusConnect database." breadcrumb={[{label:"Admin"},{label:"Dashboard"}]}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Students" value={stats.students??"—"} icon={Users} tone="primary"/><StatCard label="Faculty" value={stats.faculty??"—"} icon={GraduationCap} tone="purple"/><StatCard label="Departments" value={stats.departments??"—"} icon={Building2} tone="success"/><StatCard label="Placement drives" value={stats.placements??"—"} icon={Briefcase} tone="warning"/></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><ChartCard title="Students by department" description="Live department counts"><SimpleBarChart data={deps.map(d=>({name:d.code,students:d.students||0}))} xKey="name" yKey="students"/></ChartCard><ChartCard title="Placement applications" description="Current application status"><SimplePieChart data={placement}/></ChartCard></div><Panel className="mt-5"><PanelHeader title="System counts" description="Current database totals"/><div className="grid gap-4 p-5 sm:grid-cols-4"><div>Assignments <b>{stats.assignments??0}</b></div><div>Events <b>{stats.events??0}</b></div><div>Announcements <b>{stats.announcements??0}</b></div><div>Drives <b>{drives.length}</b></div></div></Panel></>;}
