import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CalendarCheck, CheckCircle2, Save, XCircle } from "lucide-react";
import { toast } from "sonner";
import { ConfirmationModal, FilterSelect, PageHeader, Panel, PanelHeader, StatCard } from "@/components/common";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { attendanceApi } from "@/api/campusApi";
import { pct } from "@/utils";
import { getStudents } from "@/api/adminApi";

export const Route=createFileRoute("/faculty/attendance")({head:()=>({meta:[{title:"Mark Attendance — CampusConnect"}]}),component:FacultyAttendance});
function FacultyAttendance(){
 const [roster,setRoster]=useState([]),[records,setRecords]=useState([]),[course,setCourse]=useState("Data Structures"),[section,setSection]=useState("CSE-3A"),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[present,setPresent]=useState({}),[confirm,setConfirm]=useState(false),[loading,setLoading]=useState(true);
 const load=async()=>{try{setLoading(true);const[s,a]=await Promise.all([getStudents(),attendanceApi.list()]);const rs=(s||[]).filter(x=>!section||x.section===section||!x.section);setRoster(rs);setRecords(a||[]);const existing=(a||[]).filter(x=>x.course===course&&x.section===section&&x.date===date);const map=Object.fromEntries(rs.map(x=>[x.id,true]));existing.forEach(x=>{map[x.studentId]=x.present});setPresent(map)}catch(e){toast.error(e.response?.data?.message||"Unable to load attendance")}finally{setLoading(false)}};
 useEffect(()=>{load()},[course,section,date]);
 const presentCount=roster.filter(s=>present[s.id]).length, absentCount=roster.length-presentCount;
 async function save(){try{const existing=records.filter(x=>x.course===course&&x.section===section&&x.date===date);const existingByStudent=new Map(existing.map(x=>[x.studentId,x]));for(const s of roster){const payload={studentId:s.id,course,date,present:!!present[s.id],section};const old=existingByStudent.get(s.id);if(old)await attendanceApi.update(old.id,payload);else await attendanceApi.create(payload)}toast.success("Attendance saved successfully");setConfirm(false);await load()}catch(e){toast.error(e.response?.data?.message||"Unable to save attendance")}}
 return <><PageHeader title="Attendance" description="Mark attendance and save it to the database." breadcrumb={[{label:"Faculty",to:"/faculty/dashboard"},{label:"Attendance"}]}/><Panel className="mb-5"><PanelHeader title="Select class" description="Course, section and date"/><div className="flex flex-wrap items-end gap-4 p-5"><FilterSelect label="Course" value={course} onChange={setCourse} options={["Data Structures","Algorithms","Operating Systems"]}/><FilterSelect label="Section" value={section} onChange={setSection} options={["CSE-3A","CSE-3B"]}/><label className="flex flex-col gap-1 text-xs font-medium text-muted-foreground">Date<Input type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-9 w-44"/></label><Button variant="outline" className="ml-auto" onClick={()=>setPresent(Object.fromEntries(roster.map(s=>[s.id,true])))}>Mark all present</Button></div></Panel>{loading?<div className="p-8 text-center text-sm text-muted-foreground">Loading roster…</div>:<><div className="mb-5 grid gap-4 sm:grid-cols-3"><StatCard label="Present" value={presentCount} icon={CheckCircle2} tone="success"/><StatCard label="Absent" value={absentCount} icon={XCircle} tone="danger"/><StatCard label="Attendance" value={`${pct(presentCount,roster.length)}%`} icon={CalendarCheck} tone="primary" hint={`${course} · ${section} · ${date}`}/></div><Panel><PanelHeader title={`${course} · ${section}`} description={`${roster.length} students · ${date}`} action={<Button onClick={()=>setConfirm(true)}><Save className="h-4 w-4"/> Save attendance</Button>}/><ul className="divide-y divide-border">{roster.map(s=><li key={s.id} className="flex flex-wrap items-center gap-4 px-5 py-3"><span className="w-32 shrink-0 font-mono text-xs text-muted-foreground">{s.rollNo}</span><span className="min-w-0 flex-1 text-sm font-medium">{s.name}</span><div className="flex gap-2"><Button size="sm" variant={present[s.id]?"default":"outline"} onClick={()=>setPresent(p=>({...p,[s.id]:true}))}><CheckCircle2 className="h-4 w-4"/> Present</Button><Button size="sm" variant={!present[s.id]?"destructive":"outline"} onClick={()=>setPresent(p=>({...p,[s.id]:false}))}><XCircle className="h-4 w-4"/> Absent</Button></div></li>)}</ul></Panel></>}</>;
}
