import { useEffect, useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { CheckCircle2, ClipboardCheck, FileText, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { ConfirmationModal, EmptyState, Field, FormModal, PageHeader, Panel, SearchBar, StatCard, StatusBadge } from "@/components/common";
import { DataTable } from "@/components/common/DataTable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { assignmentsApi, submissionsApi, getCurrentSession } from "@/api/campusApi";
import { formatDate } from "@/utils";

export const Route=createFileRoute("/faculty/assignments")({head:()=>({meta:[{title:"Manage Assignments — CampusConnect"}]}),component:FacultyAssignments});
const blank={title:"",course:"Data Structures",section:"CSE-3A",description:"",dueDate:"",maxMarks:20,status:"Open"};
function FacultyAssignments(){
 const [rows,setRows]=useState([]),[subs,setSubs]=useState([]),[query,setQuery]=useState(""),[open,setOpen]=useState(false),[remove,setRemove]=useState(null),[form,setForm]=useState(blank);
 const load=async()=>{try{const[a,s]=await Promise.all([assignmentsApi.list(),submissionsApi.list()]);setRows(a||[]);setSubs(s||[])}catch(e){toast.error(e.response?.data?.message||"Unable to load assignments")}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(a=>(a.title||"").toLowerCase().includes(query.toLowerCase())||(a.course||"").toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const cols=[{key:"title",header:"Assignment",render:a=><div><p className="font-medium">{a.title}</p><p className="text-caption">{a.course} · {a.section}</p></div>},{key:"due",header:"Due date",render:a=>formatDate(a.dueDate)},{key:"subs",header:"Submissions",render:a=>subs.filter(s=>s.assignmentId===a.id).length},{key:"status",header:"Status",render:a=><StatusBadge label={a.status||"Open"} tone={a.status==="Closed"?"neutral":"info"}/>},{key:"actions",header:"Actions",render:a=><div className="flex gap-1"><Button asChild variant="ghost" size="sm"><Link to="/faculty/assignments/$id/submissions" params={{id:String(a.id)}}>Submissions</Link></Button><Button variant="ghost" size="sm" className="text-destructive" onClick={()=>setRemove(a)}><Trash2 className="h-4 w-4"/></Button></div>}];
 async function save(){if(!form.title.trim()||!form.dueDate)return toast.error("Title and due date are required");try{const session=getCurrentSession();await assignmentsApi.create({...form,faculty:session?.name||"Faculty",maxMarks:Number(form.maxMarks)||0});toast.success("Assignment published");setOpen(false);setForm(blank);load()}catch(e){toast.error(e.response?.data?.message||"Unable to create assignment")}}
 async function del(){try{await assignmentsApi.remove(remove.id);toast.success("Assignment deleted");setRemove(null);load()}catch(e){toast.error(e.response?.data?.message||"Unable to delete assignment")}}
 return <><PageHeader title="Assignments" description="Create assignments and review submissions." breadcrumb={[{label:"Faculty",to:"/faculty/dashboard"},{label:"Assignments"}]} actions={<Button onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/> Create Assignment</Button>}/><div className="grid gap-4 sm:grid-cols-4"><StatCard label="Total" value={rows.length} icon={FileText} tone="primary"/><StatCard label="Open" value={rows.filter(a=>a.status!=="Closed").length} icon={FileText} tone="warning"/><StatCard label="Submissions" value={subs.length} icon={ClipboardCheck} tone="danger"/><StatCard label="Graded" value={subs.filter(s=>s.status==="Graded"||s.marks!=null).length} icon={CheckCircle2} tone="success"/></div><Panel className="mt-6"><div className="border-b border-border p-4"><SearchBar value={query} onChange={setQuery} placeholder="Search assignments…"/></div><DataTable columns={cols} rows={filtered} caption="Assignments"/></Panel><FormModal open={open} onOpenChange={setOpen} wide title="Create assignment" submitLabel="Publish assignment" onSubmit={save}><Field label="Title"><Input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Course"><Input value={form.course} onChange={e=>setForm({...form,course:e.target.value})}/></Field><Field label="Section"><Input value={form.section} onChange={e=>setForm({...form,section:e.target.value})}/></Field><Field label="Due date"><Input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Field><Field label="Max marks"><Input type="number" value={form.maxMarks} onChange={e=>setForm({...form,maxMarks:e.target.value})}/></Field></div><Field label="Description"><Textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field></FormModal><ConfirmationModal open={remove} onOpenChange={v=>!v&&setRemove(null)} destructive title="Delete assignment?" description={`Delete ${remove?.title||""}?`} confirmLabel="Delete" onConfirm={del}/></>;
}
