import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Download, FileText, Trash2, Upload } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, Panel, StatCard, StatusBadge, FormModal, Field, EmptyState } from "@/components/common";
import { DataTable } from "@/components/common/DataTable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { materialsApi, getCurrentSession } from "@/api/campusApi";
import { formatDate } from "@/utils";

export const Route = createFileRoute("/faculty/materials")({ head: () => ({ meta: [{ title: "Study Materials — CampusConnect" }] }), component: Materials });
function Materials() {
    const [rows, setRows] = useState([]), [open, setOpen] = useState(false), [form, setForm] = useState({ title: "", subject: "", course: "", type: "PDF", fileUrl: "", description: "" });
    const load = async () => { try { setRows(await materialsApi.list() || []) } catch (e) { toast.error(e.response?.data?.message || "Unable to load materials") } }; useEffect(() => { load() }, []);
    const cols = [{ key: "title", header: "Material", render: m => <div><p className="font-medium">{m.title}</p><p className="text-caption">{m.subject || m.course || ""}</p></div> }, { key: "type", header: "Type", render: m => <StatusBadge label={m.type || "File"} tone="info" /> }, { key: "uploaded", header: "Uploaded", render: m => formatDate(m.uploadedAt) }, { key: "action", header: "", render: m => <div className="flex gap-1">{m.fileUrl ? <Button asChild variant="ghost" size="sm"><a href={m.fileUrl} target="_blank" rel="noreferrer"><Download className="h-4 w-4" /></a></Button> : null}<Button variant="ghost" size="sm" className="text-destructive" onClick={async () => { try { await materialsApi.remove(m.id); toast.success("Material deleted"); load() } catch (e) { toast.error("Unable to delete material") } }}><Trash2 className="h-4 w-4" /></Button></div> }];
    async function save() { if (!form.title.trim()) return toast.error("Title is required"); try { const s = getCurrentSession(); await materialsApi.create({ ...form, uploadedBy: s?.name || "Faculty", uploadedAt: new Date().toISOString() }); toast.success("Material saved"); setOpen(false); setForm({ title: "", subject: "", course: "", type: "PDF", fileUrl: "", description: "" }); load() } catch (e) { toast.error(e.response?.data?.message || "Unable to save material") } }
    return <><PageHeader title="Study Materials" description="Manage course notes, links and reference files." breadcrumb={[{ label: "Faculty", to: "/faculty/dashboard" }, { label: "Materials" }]} actions={<Button onClick={() => setOpen(true)}><Upload className="h-4 w-4" /> Add Material</Button>} /><div className="grid gap-4 sm:grid-cols-3"><StatCard label="Files shared" value={rows.length} icon={FileText} tone="primary" /><StatCard label="Subjects" value={new Set(rows.map(r => r.subject).filter(Boolean)).size} icon={FileText} tone="purple" /><StatCard label="Linked files" value={rows.filter(r => r.fileUrl).length} icon={Download} tone="success" /></div><Panel className="mt-6"><DataTable columns={cols} rows={rows} caption="Study materials" empty={<EmptyState title="No materials" description="Add a course material or resource link." />} /></Panel><FormModal open={open} onOpenChange={setOpen} title="Add material" submitLabel="Save material" onSubmit={save}><Field label="Title"><Input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Subject"><Input value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} /></Field><Field label="Course"><Input value={form.course} onChange={e => setForm({ ...form, course: e.target.value })} /></Field><Field label="Type"><Input value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} /></Field><Field label="File / resource URL"><Input value={form.fileUrl} onChange={e => setForm({ ...form, fileUrl: e.target.value })} placeholder="https://…" /></Field></div><Field label="Description"><Textarea rows={3} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field></FormModal></>;
}
