import { useEffect, useState } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { BookOpen, ClipboardCheck, FileText, MapPin, Users } from "lucide-react";
import { toast } from "sonner";
import { PageHeader, Panel, PanelHeader, StatCard, StatusBadge } from "@/components/common";
import { Button } from "@/components/ui/button";
import { ChartCard, SimpleBarChart, SimplePieChart } from "@/components/charts";
import { assignmentsApi, submissionsApi, timetableApi, attendanceApi, announcementsApi } from "@/api/campusApi";
import { getStudents } from "@/api/adminApi";

export const Route=createFileRoute("/faculty/dashboard")({head:()=>({meta:[{title:"Faculty Dashboard — CampusConnect"}]}),component:FacultyDashboard});
function FacultyDashboard(){const [d,setD]=useState({assignments:[],subs:[],timetable:[],attendance:[],announcements:[],students:[]});const nav=useNavigate();useEffect(()=>{Promise.all([assignmentsApi.list(),submissionsApi.list(),timetableApi.list(),attendanceApi.list(),announcementsApi.list(),getStudents()]).then(([a,s,t,att,n,st])=>setD({assignments:a||[],subs:s||[],timetable:t||[],attendance:att||[],announcements:n||[],students:st||[]})).catch(e=>toast.error(e.response?.data?.message||"Unable to load dashboard"))},[]);const day=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][new Date().getDay()];const today=d.timetable.filter(x=>x.day===day);const sectionNames=[...new Set(d.attendance.map(x=>x.section).filter(Boolean))];const sec=sectionNames.map(s=>{const r=d.attendance.filter(x=>x.section===s);return {name:s,attendance:r.length?Math.round(r.filter(x=>x.present).length/r.length*100):0}});return <><PageHeader title="Faculty Dashboard" description="Live teaching data from CampusConnect." breadcrumb={[{label:"Faculty"},{label:"Dashboard"}]}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Today's classes" value={today.length} icon={BookOpen} tone="primary" onClick={()=>nav({to:"/faculty/classes"})}/><StatCard label="Students" value={d.students.length} icon={Users} tone="purple" onClick={()=>nav({to:"/faculty/students"})}/><StatCard label="Assignments" value={d.assignments.length} icon={FileText} tone="success" onClick={()=>nav({to:"/faculty/assignments"})}/><StatCard label="Pending reviews" value={d.subs.filter(s=>s.marks==null).length} icon={ClipboardCheck} tone="warning"/></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><ChartCard title="Attendance by section" description="Calculated from saved records"><SimpleBarChart data={sec} xKey="name" yKey="attendance"/></ChartCard><ChartCard title="Submission status" description="All assignments"><SimplePieChart data={[{name:"Graded",value:d.subs.filter(s=>s.marks!=null).length},{name:"Pending",value:d.subs.filter(s=>s.marks==null).length}]}/></ChartCard></div><Panel className="mt-5"><PanelHeader title="Today's classes" action={<Button asChild variant="outline"><Link to="/faculty/attendance">Mark attendance</Link></Button>}/><ul className="divide-y divide-border">{today.map(c=><li key={c.id} className="flex flex-wrap items-center gap-4 px-5 py-4"><span className="w-32">{c.startTime} - {c.endTime}</span><div className="flex-1"><p className="font-medium">{c.course} · {c.section}</p><p className="text-caption"><MapPin className="mr-1 inline h-3 w-3"/>{c.room}</p></div><StatusBadge label="Scheduled" tone="info"/></li>)}</ul></Panel></>;}
