spring.application.name=campusconnect-backend

server.port=8080
server.address=0.0.0.0
# ===============================
# PostgreSQL / Supabase
# ===============================
spring.datasource.url=jdbc:postgresql://db.qqzkepikkpqchcibffcs.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=CampusConnect@123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT
# ===============================
app.jwt.secret=CampusConnectSuperSecretKeyForJwt2026ChangeThisInProduction123456789
app.jwt.expiration-ms=86400000

# ===============================
# File uploads
# ===============================
app.upload.dir=uploads
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB