import { useEffect, useState } from "react";
import { KeyRound, Mail, Pencil, Phone } from "lucide-react";
import { toast } from "sonner";
import { Avatar, Field, FormModal, PageHeader, Panel, PanelHeader, StatusBadge } from "@/components/common";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/lib/auth";
import { roleLabel } from "@/components/layout/nav";
import { userApi } from "@/api/campusApi";

export function ProfilePage(){
 const {user,updateUser}=useAuth();const [profile,setProfile]=useState(null),[editing,setEditing]=useState(false),[pwOpen,setPwOpen]=useState(false),[form,setForm]=useState({name:"",phone:""}),[pw,setPw]=useState({current:"",next:"",confirm:""}),[pwError,setPwError]=useState("");
 useEffect(()=>{userApi.me().then(p=>{setProfile(p);setForm({name:p.name||"",phone:p.phone||""});updateUser({name:p.name,identifier:p.identifier||"",department:p.department||"",extra:{...(user?.extra||{}),Phone:p.phone||""}})}).catch(()=>{})},[]);
 if(!user)return null;const p=profile||{...user,identifier:user.identifier,department:user.department,phone:user.extra?.Phone||""};
 async function save(){try{const x=await userApi.updateProfile(form);setProfile(x);updateUser({name:x.name,identifier:x.identifier||"",department:x.department||"",extra:{...(user.extra||{}),Phone:x.phone||""}});toast.success("Profile updated");setEditing(false)}catch(e){toast.error(e.response?.data?.message||"Unable to update profile")}}
 async function changePassword(){if(pw.next.length<8)return setPwError("New password must be at least 8 characters");if(pw.next!==pw.confirm)return setPwError("Passwords do not match");try{await userApi.changePassword({currentPassword:pw.current,newPassword:pw.next});toast.success("Password updated");setPwOpen(false);setPw({current:"",next:"",confirm:""});setPwError("")}catch(e){setPwError(e.response?.data?.message||"Unable to change password")}}
 return <><PageHeader title="My Profile" description="Your account and contact information." breadcrumb={[{label:roleLabel[user.role],to:`/${user.role}/dashboard`},{label:"Profile"}]} actions={<><Button variant="outline" onClick={()=>setPwOpen(true)}><KeyRound className="h-4 w-4"/> Change password</Button><Button onClick={()=>setEditing(true)}><Pencil className="h-4 w-4"/> Edit profile</Button></>}/><div className="grid gap-5 lg:grid-cols-3"><Panel className="p-6 text-center"><div className="flex justify-center"><Avatar name={p.name} size="lg"/></div><h2 className="mt-4 text-section-heading">{p.name}</h2><p className="text-caption">{p.identifier||"—"} · {p.department||"—"}</p><div className="mt-3 flex justify-center"><StatusBadge label={roleLabel[user.role]} tone="info"/></div><div className="mt-6 space-y-2 text-left text-sm"><p className="text-muted-foreground"><Mail className="mr-2 inline h-4 w-4"/>{p.email}</p><p className="text-muted-foreground"><Phone className="mr-2 inline h-4 w-4"/>{p.phone||"—"}</p></div></Panel><Panel className="lg:col-span-2"><PanelHeader title="Account details"/><dl className="grid gap-x-8 gap-y-5 p-6 sm:grid-cols-2">{[["Full name",p.name],["Email",p.email],["ID",p.identifier||"—"],["Department",p.department||"—"],["Phone",p.phone||"—"]].map(([k,v])=><div key={k}><dt className="text-caption">{k}</dt><dd className="mt-0.5 text-sm font-medium">{v}</dd></div>)}</dl></Panel></div><FormModal open={editing} onOpenChange={setEditing} title="Edit profile" submitLabel="Save changes" onSubmit={save}><Field label="Full name"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Email"><Input value={p.email} disabled/></Field><Field label="Phone"><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field></FormModal><FormModal open={pwOpen} onOpenChange={setPwOpen} title="Change password" submitLabel="Update password" onSubmit={changePassword}><Field label="Current password"><Input type="password" value={pw.current} onChange={e=>setPw({...pw,current:e.target.value})}/></Field><Field label="New password" error={pwError}><Input type="password" value={pw.next} onChange={e=>setPw({...pw,next:e.target.value})}/></Field><Field label="Confirm password"><Input type="password" value={pw.confirm} onChange={e=>setPw({...pw,confirm:e.target.value})}/></Field></FormModal></>;
}
