/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFacultyRouteImport } from './routes/admin.faculty'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPlacementsRouteImport } from './routes/admin.placements'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as FacultyAnnouncementsRouteImport } from './routes/faculty.announcements'
import { Route as FacultyAssignmentsRouteImport } from './routes/faculty.assignments'
import { Route as FacultyAttendanceRouteImport } from './routes/faculty.attendance'
import { Route as FacultyClassesRouteImport } from './routes/faculty.classes'
import { Route as FacultyDashboardRouteImport } from './routes/faculty.dashboard'
import { Route as FacultyEventsRouteImport } from './routes/faculty.events'
import { Route as FacultyMaterialsRouteImport } from './routes/faculty.materials'
import { Route as FacultyNotificationsRouteImport } from './routes/faculty.notifications'
import { Route as FacultyProfileRouteImport } from './routes/faculty.profile'
import { Route as FacultyStudentsRouteImport } from './routes/faculty.students'
import { Route as StudentAcademicsRouteImport } from './routes/student.academics'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentEventsRouteImport } from './routes/student.events'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentPlacementsRouteImport } from './routes/student.placements'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as FacultyAssignmentsIdSubmissionsRouteImport } from './routes/faculty.assignments.$id.submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacementsRoute = AdminPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const FacultyAnnouncementsRoute = FacultyAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyAssignmentsRoute = FacultyAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyAttendanceRoute = FacultyAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyClassesRoute = FacultyClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyDashboardRoute = FacultyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyEventsRoute = FacultyEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyMaterialsRoute = FacultyMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyNotificationsRoute = FacultyNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyProfileRoute = FacultyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyRoute,
} as any)
const FacultyStudentsRoute = FacultyStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => FacultyRoute,
} as any)
const StudentAcademicsRoute = StudentAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPlacementsRoute = StudentPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)
const FacultyAssignmentsIdSubmissionsRoute =
  FacultyAssignmentsIdSubmissionsRouteImport.update({
    id: '/$id/submissions',
    path: '/$id/submissions',
    getParentRoute: () => FacultyAssignmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/faculty/announcements': typeof FacultyAnnouncementsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRouteWithChildren
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/classes': typeof FacultyClassesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/events': typeof FacultyEventsRoute
  '/faculty/materials': typeof FacultyMaterialsRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/events': typeof StudentEventsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/placements': typeof StudentPlacementsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/faculty/assignments/$id/submissions': typeof FacultyAssignmentsIdSubmissionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/faculty/announcements': typeof FacultyAnnouncementsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRouteWithChildren
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/classes': typeof FacultyClassesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/events': typeof FacultyEventsRoute
  '/faculty/materials': typeof FacultyMaterialsRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/events': typeof StudentEventsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/placements': typeof StudentPlacementsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/faculty/assignments/$id/submissions': typeof FacultyAssignmentsIdSubmissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/faculty': typeof FacultyRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/faculty/announcements': typeof FacultyAnnouncementsRoute
  '/faculty/assignments': typeof FacultyAssignmentsRouteWithChildren
  '/faculty/attendance': typeof FacultyAttendanceRoute
  '/faculty/classes': typeof FacultyClassesRoute
  '/faculty/dashboard': typeof FacultyDashboardRoute
  '/faculty/events': typeof FacultyEventsRoute
  '/faculty/materials': typeof FacultyMaterialsRoute
  '/faculty/notifications': typeof FacultyNotificationsRoute
  '/faculty/profile': typeof FacultyProfileRoute
  '/faculty/students': typeof FacultyStudentsRoute
  '/student/academics': typeof StudentAcademicsRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/events': typeof StudentEventsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/placements': typeof StudentPlacementsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/faculty/assignments/$id/submissions': typeof FacultyAssignmentsIdSubmissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faculty'
    | '/forgot-password'
    | '/login'
    | '/student'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/notifications'
    | '/admin/placements'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/students'
    | '/faculty/announcements'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/classes'
    | '/faculty/dashboard'
    | '/faculty/events'
    | '/faculty/materials'
    | '/faculty/notifications'
    | '/faculty/profile'
    | '/faculty/students'
    | '/student/academics'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/events'
    | '/student/notifications'
    | '/student/placements'
    | '/student/profile'
    | '/student/timetable'
    | '/faculty/assignments/$id/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faculty'
    | '/forgot-password'
    | '/login'
    | '/student'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/notifications'
    | '/admin/placements'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/students'
    | '/faculty/announcements'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/classes'
    | '/faculty/dashboard'
    | '/faculty/events'
    | '/faculty/materials'
    | '/faculty/notifications'
    | '/faculty/profile'
    | '/faculty/students'
    | '/student/academics'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/events'
    | '/student/notifications'
    | '/student/placements'
    | '/student/profile'
    | '/student/timetable'
    | '/faculty/assignments/$id/submissions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faculty'
    | '/forgot-password'
    | '/login'
    | '/student'
    | '/admin/announcements'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/events'
    | '/admin/faculty'
    | '/admin/notifications'
    | '/admin/placements'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/students'
    | '/faculty/announcements'
    | '/faculty/assignments'
    | '/faculty/attendance'
    | '/faculty/classes'
    | '/faculty/dashboard'
    | '/faculty/events'
    | '/faculty/materials'
    | '/faculty/notifications'
    | '/faculty/profile'
    | '/faculty/students'
    | '/student/academics'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/events'
    | '/student/notifications'
    | '/student/placements'
    | '/student/profile'
    | '/student/timetable'
    | '/faculty/assignments/$id/submissions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  FacultyRoute: typeof FacultyRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/placements': {
      id: '/admin/placements'
      path: '/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AdminPlacementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/faculty/announcements': {
      id: '/faculty/announcements'
      path: '/announcements'
      fullPath: '/faculty/announcements'
      preLoaderRoute: typeof FacultyAnnouncementsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/assignments': {
      id: '/faculty/assignments'
      path: '/assignments'
      fullPath: '/faculty/assignments'
      preLoaderRoute: typeof FacultyAssignmentsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/attendance': {
      id: '/faculty/attendance'
      path: '/attendance'
      fullPath: '/faculty/attendance'
      preLoaderRoute: typeof FacultyAttendanceRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/classes': {
      id: '/faculty/classes'
      path: '/classes'
      fullPath: '/faculty/classes'
      preLoaderRoute: typeof FacultyClassesRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/dashboard': {
      id: '/faculty/dashboard'
      path: '/dashboard'
      fullPath: '/faculty/dashboard'
      preLoaderRoute: typeof FacultyDashboardRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/events': {
      id: '/faculty/events'
      path: '/events'
      fullPath: '/faculty/events'
      preLoaderRoute: typeof FacultyEventsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/materials': {
      id: '/faculty/materials'
      path: '/materials'
      fullPath: '/faculty/materials'
      preLoaderRoute: typeof FacultyMaterialsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/notifications': {
      id: '/faculty/notifications'
      path: '/notifications'
      fullPath: '/faculty/notifications'
      preLoaderRoute: typeof FacultyNotificationsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/profile': {
      id: '/faculty/profile'
      path: '/profile'
      fullPath: '/faculty/profile'
      preLoaderRoute: typeof FacultyProfileRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/faculty/students': {
      id: '/faculty/students'
      path: '/students'
      fullPath: '/faculty/students'
      preLoaderRoute: typeof FacultyStudentsRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/student/academics': {
      id: '/student/academics'
      path: '/academics'
      fullPath: '/student/academics'
      preLoaderRoute: typeof StudentAcademicsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/events': {
      id: '/student/events'
      path: '/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/placements': {
      id: '/student/placements'
      path: '/placements'
      fullPath: '/student/placements'
      preLoaderRoute: typeof StudentPlacementsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
    '/faculty/assignments/$id/submissions': {
      id: '/faculty/assignments/$id/submissions'
      path: '/$id/submissions'
      fullPath: '/faculty/assignments/$id/submissions'
      preLoaderRoute: typeof FacultyAssignmentsIdSubmissionsRouteImport
      parentRoute: typeof FacultyAssignmentsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlacementsRoute: typeof AdminPlacementsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlacementsRoute: AdminPlacementsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface FacultyAssignmentsRouteChildren {
  FacultyAssignmentsIdSubmissionsRoute: typeof FacultyAssignmentsIdSubmissionsRoute
}

const FacultyAssignmentsRouteChildren: FacultyAssignmentsRouteChildren = {
  FacultyAssignmentsIdSubmissionsRoute: FacultyAssignmentsIdSubmissionsRoute,
}

const FacultyAssignmentsRouteWithChildren =
  FacultyAssignmentsRoute._addFileChildren(FacultyAssignmentsRouteChildren)

interface FacultyRouteChildren {
  FacultyAnnouncementsRoute: typeof FacultyAnnouncementsRoute
  FacultyAssignmentsRoute: typeof FacultyAssignmentsRouteWithChildren
  FacultyAttendanceRoute: typeof FacultyAttendanceRoute
  FacultyClassesRoute: typeof FacultyClassesRoute
  FacultyDashboardRoute: typeof FacultyDashboardRoute
  FacultyEventsRoute: typeof FacultyEventsRoute
  FacultyMaterialsRoute: typeof FacultyMaterialsRoute
  FacultyNotificationsRoute: typeof FacultyNotificationsRoute
  FacultyProfileRoute: typeof FacultyProfileRoute
  FacultyStudentsRoute: typeof FacultyStudentsRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyAnnouncementsRoute: FacultyAnnouncementsRoute,
  FacultyAssignmentsRoute: FacultyAssignmentsRouteWithChildren,
  FacultyAttendanceRoute: FacultyAttendanceRoute,
  FacultyClassesRoute: FacultyClassesRoute,
  FacultyDashboardRoute: FacultyDashboardRoute,
  FacultyEventsRoute: FacultyEventsRoute,
  FacultyMaterialsRoute: FacultyMaterialsRoute,
  FacultyNotificationsRoute: FacultyNotificationsRoute,
  FacultyProfileRoute: FacultyProfileRoute,
  FacultyStudentsRoute: FacultyStudentsRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface StudentRouteChildren {
  StudentAcademicsRoute: typeof StudentAcademicsRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentEventsRoute: typeof StudentEventsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentPlacementsRoute: typeof StudentPlacementsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAcademicsRoute: StudentAcademicsRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentEventsRoute: StudentEventsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentPlacementsRoute: StudentPlacementsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentTimetableRoute: StudentTimetableRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  FacultyRoute: FacultyRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
